# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  METRICS_GIST: "516152e14bb724ad66abe542935668ab"

jobs:
  metrics-terminal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: terminal1.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ env.METRICS_GIST }}
          template: terminal
          base: header, activity, repositories, metadata
          config_display: columns
          config_timezone: Asia/Tokyo

  metrics-activity1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: activity1.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ env.METRICS_GIST }}
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_skipped: Com-Pro
          plugin_languages_threshold: 2%
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: commit

  metrics-activity2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: activity2.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ env.METRICS_GIST }}
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_stars: yes
          plugin_stars_limit: 2
