# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  METRICS_GIST: "516152e14bb724ad66abe542935668ab"

jobs:
  metrics-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: profile.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ras0q
          output_action: gist
          committer_gist: ${{ env.METRICS_GIST }}
          template: classic
          config_order: base.header, languages, base.activity+community, base.repositories, notable
          config_timezone: Asia/Tokyo
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_skipped: Com-Pro,dotfiles
          plugin_languages_threshold: 2%
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_from: all
          plugin_notable_indepth: yes

  snk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          gist_id: ${{ env.METRICS_GIST }}
          gist_file_name: github-snake.svg
          file_path: dist/github-snake.svg
          file_type: binary
      - uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          gist_id: ${{ env.METRICS_GIST }}
          gist_file_name: github-snake-dark.svg
          file_path: dist/github-snake-dark.svg
          file_type: binary
