# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  metrics-terminal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: terminal1.svg
          user: ras0q
          template: terminal
          base: header, activity, community, repositories, metadata
          config_display: columns
          config_timezone: Asia/Tokyo

  metrics-activity1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: activity1.svg
          user: ras0q
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_skipped: Com-Pro
          plugin_languages_threshold: 2%
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: commit
          
  metrics-activity2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: activity2.svg
          user: ras0q
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_stars: yes
          plugin_stars_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 5
          plugin_topics_mode: starred
          plugin_topics_sort: stars
